apiVersion: nuclio.io/v1beta1
kind: Function
metadata:
  name: parcel-svg-geojson2svg
  namespace: fast-platform
  labels:
    platform: fast
    module: core
    domain: gis
    api: parcel-svg
    app: geojson2svg
spec:
  alias: latest
  description: Generate a SVG from a GeoJSON
  handler: main:handler
  image: eufast/parcel-svg-geojson2svg:0.1.0
  replicas: 2
  maxReplicas: 5
  targetCPU: 80
  runtime: python:3.6
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi 
  triggers:
    http:
      kind: http
      maxWorkers: 10
  version: -1
status:
  state: waitingForResourceConfiguration
